#!/usr/bin/env node
/**
 * session-start.js
 * SessionStart hook -- fires at the beginning of every Claude Code session.
 *
 * Reads and prints context files in priority order so Claude Code picks them
 * up as session context:
 *
 *   1. HANDOFF.md          -- last-session handoff (generated by build-handoff.js)
 *   2. TASK_BOARD.md       -- current task board (non-Done sections only)
 *   3. .nfl/memory.json    -- durable cross-session state
 *
 * Skip conditions:
 *   - NFL_SKIP_HOOKS=true  (CI / overnight pipeline)
 *   - CI=true
 *
 * Output goes to stdout. Claude Code surfaces this as session-start context.
 * The hook never hard-fails -- exits 0 on any error so sessions are never blocked.
 */

import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = dirname(__filename);
const WORKSPACE_ROOT = join(__dirname, '..', '..');

if (process.env.NFL_SKIP_HOOKS === 'true' || process.env.CI === 'true') {
  process.exit(0);
}

const NFL_DIR      = join(WORKSPACE_ROOT, '.nfl');
const HANDOFF_FILE = join(WORKSPACE_ROOT, 'HANDOFF.md');
const TASK_BOARD   = join(WORKSPACE_ROOT, 'TASK_BOARD.md');
const MEMORY_FILE  = join(NFL_DIR, 'memory.json');

/**
 * Read a file safely. Returns null if missing or unreadable.
 * @param {string} filePath
 * @returns {string|null}
 */
function safeRead(filePath) {
  if (!existsSync(filePath)) return null;
  try {
    return readFileSync(filePath, 'utf8').trim();
  } catch {
    return null;
  }
}

/**
 * Format memory.json into a readable summary.
 * @param {string} raw - raw JSON string
 * @returns {string}
 */
function formatMemory(raw) {
  try {
    const mem   = JSON.parse(raw);
    const lines = ['## NFL Dashboard Cross-Session Memory\n'];

    if (mem.last_session_date) lines.push(`**Last session:** ${mem.last_session_date}`);
    if (mem.total_sessions)    lines.push(`**Total sessions:** ${mem.total_sessions}`);

    if (Array.isArray(mem.open_threads) && mem.open_threads.length > 0) {
      lines.push('\n**Open threads:**');
      for (const t of mem.open_threads) lines.push(`- ${t}`);
    }
    if (Array.isArray(mem.active_agents) && mem.active_agents.length > 0) {
      lines.push('\n**Active agents:**');
      for (const a of mem.active_agents) lines.push(`- ${a}`);
    }
    if (mem.notes) lines.push(`\n**Notes:** ${mem.notes}`);

    return lines.join('\n');
  } catch {
    return `## NFL Dashboard Cross-Session Memory\n\n${raw}`;
  }
}

function main() {
  const sections = [];

  // 1. HANDOFF.md -- highest priority; generated by build-handoff.js at session end
  const handoff = safeRead(HANDOFF_FILE);
  if (handoff) {
    sections.push(handoff);
  } else {
    sections.push('## Session Resume\n\n_No prior session handoff found. Starting fresh._');
  }

  // 2. TASK_BOARD.md -- skip Done sections to keep output lean
  const taskBoard = safeRead(TASK_BOARD);
  if (taskBoard) {
    const lines    = taskBoard.split('\n');
    const filtered = [];
    let inDone     = false;

    for (const line of lines) {
      if (/^## Done/i.test(line))  inDone = true;
      else if (/^## /.test(line))  inDone = false;
      if (!inDone) filtered.push(line);
    }

    const trimmed = filtered.join('\n').trim();
    if (trimmed) sections.push(`---\n\n${trimmed}`);
  }

  // 3. memory.json -- durable state
  const memory = safeRead(MEMORY_FILE);
  if (memory) sections.push(`---\n\n${formatMemory(memory)}`);

  if (sections.length > 0) process.stdout.write(sections.join('\n\n') + '\n');
}

try {
  main();
} catch {
  // Never block a session start
  process.exit(0);
}
